name = input("Hello Sir/Madam, Please enter your name: ")
age = input("Amazing now let's move on to your age, Please enter your age: ")
city = input("Wow you are really young! Now Let's move on to your city, please enter your city: ")
Favourite_food = input("Nice place to live in ! Can I know your favourite food Sir/Madam: ")
Favourite_book = input("You have a great taste in food! I am curious to know about the name of your favourite book: ")
print("Thank you for providing your details. Here is the summary of the information you provided:")
print("Based on the information you provided")
print("Your name is: ",name)
print("You are ",age,"years young")
print("Your lovely city is: ",city)
print("Your tongue is obsessed with the taste of: ",Favourite_food)
print("You find the joy of reading in: ",Favourite_book)