Name = input("What is your name dear user? ")
English_marks = int(input("How much have you scored in the English Language subject? "))
Maths_marks = int(input("Nice, What about your score in the Mathematics subject? "))
Science_marks = int(input("Okay, moving on to your score in the Science subject, how much have you scored? "))
print("Thankyou we are pocessing your data and giving you your final result")
print("Based on the information you provided")
print("Your name is: ",Name)
print("Your score in English is: ",English_marks)
print("Your score in Mathematics is: ",Maths_marks)
print("Your score in Science is: ",Science_marks)
print("Your total score is: ",English_marks + Maths_marks + Science_marks)
print("Your average marks is: ", (English_marks + Maths_marks + Science_marks) / 3, round,2)
